name: "Stale Cleanup"

on:
  schedule:
    # Runs at midnight UTC every Wednesday
    - cron: "0 0 * * 3"
  workflow_dispatch:

permissions: {}

jobs:
  stale:
    uses: braintree/web-sdk-github-actions/.github/workflows/stale-cleanup.yml@7a0129438dde00a728cc851ce2cab9820bb264ed
    permissions:
      actions: write
      issues: write
      pull-requests: write
      contents: write
